  Python_c.cpp
d:\work\python_c\python_c\python_c\python_c.cpp(17): warning C4101: pValue: неиспользованная локальная переменная
LINK : fatal error LNK1104: не удается открыть файл "python38_d.lib"
